backend:
  name: github
  repo: motoi/circular-lab-hiroshima
  branch: main

media_folder: "images"

collections:
  - name: "news"
    label: "お知らせ"
    folder: "_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "本文", name: "body", widget: "markdown"}
